apiVersion: apps/v1

kind: Deployment
metadeta:
  name: ex7-test-coverage
  labels:
    app: ex7-test-coverage
spec:
  selector:
    matchLabels:
      app: ex7-test-coverage
    replicas: 1
    template:
      metadata:
        name: ex7-test-coverage
        labels:
          app: ex7-test-coverage
      spec:
        containers:
          - name: ex7-test-coverage
            image: local/ex7-test-coverage:latest
            imagePullPolicy: Never
            ports:
              -containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ex7-test-coverage
  labels:
    app: ex7-test-coverage
spec:
  type: NodePort
  selector:
    app: ex7-test-coverage
    ports:
      - name: http
        port: 8080
        targetPort: 8080